name: Auto-update version.txt after PR merge

on:
  pull_request:
    types: [closed]

jobs:
  update-version:
    if: github.event.pull_request.merged == true && github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit SHA
        id: sha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Update version.txt
        run: |
          echo "Program: Ksieg-OCR" > version.txt
          echo "Commit: ${{ steps.sha.outputs.sha }}" >> version.txt
          echo "PR: ${{ github.event.pull_request.number }}" >> version.txt

      - name: Commit & push version.txt
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add version.txt
          git commit -m "Auto-update version.txt after PR #${{ github.event.pull_request.number }} merge"
          git push